# grafana MCP Server Registry Entry
# Auto-imported from ToolHive registry.json
# 
# Original source: https://github.com/stacklok/toolhive
# Import timestamp: 2025-08-11T09:21:39Z
# ---
name: grafana
image: docker.io/mcp/grafana:latest
description: Provides access to your Grafana instance and the surrounding ecosystem, enabling dashboard search, datasource queries, alerting management, incident response, and Sift investigations.
tier: Official
status: Active
transport: sse
targetport: 8000
permissions:
    name: ""
    read: []
    write: []
    network:
        outbound:
            insecureallowall: true
            allowhost: []
            allowport:
                - 443
tools:
    - list_teams
    - search_dashboards
    - get_dashboard_by_uid
    - update_dashboard
    - get_dashboard_panel_queries
    - list_datasources
    - get_datasource_by_uid
    - get_datasource_by_name
    - query_prometheus
    - list_prometheus_metric_metadata
    - list_prometheus_metric_names
    - list_prometheus_label_names
    - list_prometheus_label_values
    - list_incidents
    - create_incident
    - add_activity_to_incident
    - resolve_incident
    - query_loki_logs
    - list_loki_label_names
    - list_loki_label_values
    - query_loki_stats
    - list_alert_rules
    - get_alert_rule_by_uid
    - list_oncall_schedules
    - get_oncall_shift
    - get_current_oncall_users
    - list_oncall_teams
    - list_oncall_users
    - get_investigation
    - get_analysis
    - list_investigations
    - find_error_pattern_logs
    - find_slow_requests
    - list_pyroscope_label_names
    - list_pyroscope_label_values
    - list_pyroscope_profile_types
    - fetch_pyroscope_profile
envvars:
    - name: GRAFANA_URL
      description: URL of the Grafana instance to connect to
      required: true
      default: ""
      secret: false
    - name: GRAFANA_API_KEY
      description: Service account token with appropriate permissions
      required: true
      default: ""
      secret: true
args: []
metadata:
    stars: 1363
    pulls: 7910
    lastupdated: "2025-08-11T00:24:59Z"
repositoryurl: https://github.com/grafana/mcp-grafana
tags:
    - grafana
    - dashboards
    - visualization
    - monitoring
    - alerting
    - prometheus
    - loki
    - tempo
    - pyroscope
    - incidents
    - observability
    - metrics
    - logs
    - traces
    - sift
    - investigations
    - oncall
dockertags: []
provenance: null
custommetadata: {}
